version: '2'
###
services:
  #_____________________________________________________
  #
  base.gateway:
    ports:
      - 80:80
      - 443:443
    environment:
      - SSL_CERT=/opt/gateway/conf.d/cert/cubbles-base-local.crt
      - SSL_CERT_KEY=/opt/gateway/conf.d/cert/cubbles-base-local.key
    volumes:
      - /mnt/sda1/tmp/base-config-local/cubbles-base-local.crt:/opt/gateway/conf.d/cert/cubbles-base-local.crt
      - /mnt/sda1/tmp/base-config-local/cubbles-base-local.key:/opt/gateway/conf.d/cert/cubbles-base-local.key
  #_____________________________________________________
  #
  base.authentication:

  #_____________________________________________________
  #
  base.userprofilemanagement:

  #_____________________________________________________
  #
  base.coredatastore:
    ports:
      - "5984:5984"
    volumes:
      - /mnt/sda1/tmp:/backups

#========================================================
# volumes
# volumes:

#
#========================================================
## networks
# networks: